### ISSUE TITLE
Running ./script/train.py on a server with CPU only

### ISSUE THREAD

**Issue by shadowdeng1994** [xqding/PEVAE_Paper#4]
Hi, 

How could I run ./script/train.py on a server with CPU only?

It would be my honors to have your reply.

Thank you!

**Comment by xqding** [comment]
You can remove/comment all the lines that look like v = v.cuda().

**Comment by shadowdeng1994** [comment]
Hi, 

I replace pytorch with pytorch-cpu. Then I got a new error like:

Traceback (most recent call last):
  File "/data/user/dsj/software/Package/PEVAE_Paper/simulated_msa/./script/train.py", line 52, in <module>
    vae.cuda()
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 680, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 680, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

What should I do now? 

Thank you! : )

**Comment by shadowdeng1994** [comment]
OK, I got it. Thank you! : )

**Comment by xqding** [comment]
Great! I will close the issue now, but feel free to reopen it if there are still problems.

**Comment by xqding** [comment]
Great! I will close the issue for now, but feel free to reopen it if there are still problems.

**Comment by shadowdeng1994** [comment]
Sorry to interrupt again. 

I commented lines 52, 64 and 65 now, but I still failed to run train.py. 

When I ran it in in the terminal, it return a error as follow.

Traceback (most recent call last):
  File "/data/user/dsj/software/Package/PEVAE_Paper/simulated_msa/./script/train.py", line 67, in <module>
    loss = (-1)*vae.compute_elbo_with_weight(msa, weight)
  File "/home/dsj/miniconda3/envs/AutoEncoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in \_\_getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VAE' object has no attribute 'compute_elbo_with_weight'

Then I ran on python session, it showed another error like,

\>\>\> from VAE_model import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'VAE_model'

Thank you for your help and support.

**Comment by xqding** [comment]
I just pushed a fix to change compute_elbo_with_weights to compute_weighted_elbo. Could you try if it works now?

For the error you saw when running it in a python shell, it is because the path to script is not added to sys.path. It should be fixed now too. Could you also try it again?

**Comment by shadowdeng1994** [comment]
Yes, it worked. Thank you! : )
![image](https://user-images.githubusercontent.com/49464233/139894256-f88055c7-eebd-471f-8f06-79cfb64fb9bc.png)

**Comment by shadowdeng1994** [comment]
Hi,

I got a new error when I tried to train with pfam_msa.

Traceback (most recent call last):
  File "/data/user/dsj/software/Package/PEVAE_Paper/pfam_msa/./script/proc_msa.py", line 64, in <module>
    seq_msa.append([aa_index[s] for s in seq_dict[k]])
  File "/data/user/dsj/software/Package/PEVAE_Paper/pfam_msa/./script/proc_msa.py", line 64, in <listcomp>
    seq_msa.append([aa_index[s] for s in seq_dict[k]])
KeyError: 'B'

How can I fix that?

Thank you!

**Comment by shadowdeng1994** [comment]
Hi, 

I have succeeded in running customized sequences, but I found the final number of data point in latent_space.pkl is less than the input sequences. 

How can I map the corresponding point in latent space for a specific input sequence?

Thank you! : )
